import * as fs from 'fs';
import * as path from 'path';
interface PricePoint { ticker: string; close: number; time: string; }
interface MetricSnapshot { earnings_per_share: number; book_value_per_share: number; }
interface TickerData { snapshot: { snapshot: MetricSnapshot }; raw: { prices: PricePoint[] }; }
interface MacroPoint { observation_date: string; observation_value: number; }
const LAKE_PATH = "/workspace/user/portfolio-engine/data/lake/";
const START_DATE = new Date("2024-01-01");
const END_DATE = new Date("2026-06-01");
const TICKERS = ["AAPL", "MSFT", "NVDA", "TM", "ASML", "HSBC", "SAP", "NVS", "UL"];
class BacktestRunner {
 priceHistory: Map<string, PricePoint[]> = new Map(); fundamentalHistory: Map<string, TickerData> = new Map(); macroHistory: Map<string, MacroPoint[]> = new Map(); portfolio = { cash: 1000000, positions: new Map<string, number>() }; history: any[] = [];
 loadData() { console.log(`Loading data for ${TICKERS.length} tickers...`); ["FEDFUNDS", "GDP", "UNRATE", "CPIAUCSL"].forEach(sid => { const p = path.join(LAKE_PATH, `fred/raw/${sid}/${sid}.csv`); if (fs.existsSync(p)) { const content = fs.readFileSync(p, 'utf8'); const lines = content.split('\n').filter(l => l.trim() !== "").slice(1); const data = lines.map(l => { const parts = l.split(','); return { observation_date: parts[2], observation_value: parseFloat(parts[3]) }; }).filter(d => !isNaN(d.observation_value)); this.macroHistory.set(sid, data); } }); TICKERS.forEach(t => { const p = path.join(LAKE_PATH, `finance_bridge/expanded_universe/${t}.json`); if (fs.existsSync(p)) { try { const data = JSON.parse(fs.readFileSync(p, 'utf8')) as TickerData; if (data && data.snapshot && data.snapshot.snapshot) { this.fundamentalHistory.set(t, data); if (data.raw && data.raw.prices) this.priceHistory.set(t, data.raw.prices); } } catch(e) {} } }); }
 getRegimeScore(date: Date): number { const ff = this.macroHistory.get("FEDFUNDS"); if (!ff) return 0; const past = ff.filter(d => new Date(d.observation_date) <= date); const latest = past[past.length - 1]; return (latest?.observation_value || 0) < 5 ? -1 : 1; }
 calculateIntrinsicValue(ticker: string): number { const data = this.fundamentalHistory.get(ticker); if (!data || !data.snapshot || !data.snapshot.snapshot) return 0; const snap = data.snapshot.snapshot; return ((snap.earnings_per_share || 0) * 30 + (snap.book_value_per_share || 0) * 2); }
 getPrice(ticker: string, date: Date): number { const prices = this.priceHistory.get(ticker); if (!prices) return 0; const past = prices.filter(p => new Date(p.time) <= date); const match = past[past.length - 1]; return match ? match.close : 0; }
 run() { this.loadData(); let current = new Date(START_DATE); while (current <= END_DATE) { const regime = this.getRegimeScore(current); const targetWeight = regime < 0 ? 0.8 : 0.6; const candidates: {ticker: string, price: number}[] = []; TICKERS.forEach(t => { const intrinsic = this.calculateIntrinsicValue(t); const price = this.getPrice(t, current); if (price > 0 && intrinsic > 0) { const mos = (intrinsic - price) / price; if (mos > -0.5) candidates.push({ticker: t, price}); } }); this.rebalance(candidates, targetWeight, current); let equityValue = 0; this.portfolio.positions.forEach((shares, t) => { equityValue += shares * this.getPrice(t, current); }); this.history.push({ date: current.toISOString().split('T')[0], cash: this.portfolio.cash, equityValue, totalValue: this.portfolio.cash + equityValue, regime, positionCount: this.portfolio.positions.size }); current.setMonth(current.getMonth() + 1); } this.save(); }
 rebalance(candidates: {ticker: string, price: number}[], targetWeight: number, date: Date) { let totalValue = this.portfolio.cash; this.portfolio.positions.forEach((shares, t) => { const p = this.getPrice(t, date); if (p > 0) totalValue += shares * p; }); const targetEquity = totalValue * targetWeight; const candTickers = candidates.map(c => c.ticker); this.portfolio.positions.forEach((shares, t) => { if (!candTickers.includes(t)) { const p = this.getPrice(t, date); if (p > 0) { this.portfolio.cash += shares * p; this.portfolio.positions.delete(t); } } }); if (candidates.length > 0) { const perStock = targetEquity / candidates.length; candidates.forEach(c => { const currentShares = this.portfolio.positions.get(c.ticker) || 0; const currentVal = currentShares * c.price; const diff = perStock - currentVal; if (diff > 0 && this.portfolio.cash >= diff) { this.portfolio.positions.set(c.ticker, currentShares + diff / c.price); this.portfolio.cash -= diff; } else if (diff < 0) { const sellShares = Math.min(currentShares, Math.abs(diff) / c.price); this.portfolio.positions.set(c.ticker, currentShares - sellShares); this.portfolio.cash += sellShares * c.price; } }); } }
 save() { const out = path.join(LAKE_PATH, "backtest_results.json"); fs.writeFileSync(out, JSON.stringify(this.history, null, 2)); console.log(`Results saved to ${out}`); const final = this.history[this.history.length - 1]; console.log(`Final Portfolio Value: $${final.totalValue.toLocaleString()}`); console.log(`Final Cash: $${final.cash.toLocaleString()}`); console.log(`Final Equity: $${final.equityValue.toLocaleString()}`); console.log(`Total Return: ${((final.totalValue - 1000000) / 10000).toFixed(2)}%`); }
}
new BacktestRunner().run();