import * as fs from 'fs';
import * as path from 'path';
interface PricePoint { ticker: string; close: number; time: string; }
interface MetricSnapshot { earnings_per_share?: number; book_value_per_share?: number; as_of?: string; report_date?: string; period_end?: string; date?: string; time?: string; }
interface FundamentalPoint { time: string; earnings_per_share: number; book_value_per_share: number; }
interface TickerData { snapshot?: { snapshot?: MetricSnapshot; as_of?: string }; raw?: { prices?: PricePoint[]; fundamentals?: any[]; metrics?: any[]; financials?: any[] }; fundamentals?: any[]; metrics?: any[] }
interface MacroPoint { observation_date: string; observation_value: number; }
const LAKE_PATH = "/workspace/user/portfolio-engine/data/lake/";
const START_DATE = new Date("2024-01-01");
const END_DATE = new Date("2026-06-01");
const TICKERS = ["AAPL", "MSFT", "NVDA", "TM", "ASML", "HSBC", "SAP", "NVS", "UL"];
class BacktestRunner {
 priceHistory: Map<string, PricePoint[]> = new Map(); fundamentalHistory: Map<string, TickerData> = new Map(); fundamentalPoints: Map<string, FundamentalPoint[]> = new Map(); macroHistory: Map<string, MacroPoint[]> = new Map(); portfolio = { cash: 1000000, positions: new Map<string, number>() }; history: any[] = [];
 private fundDate(row: any): string | null { const v = row?.as_of || row?.report_date || row?.period_end || row?.date || row?.time || row?.observation_date || row?.fiscalDateEnding; return v ? String(v) : null; }
 private toFundPoint(row: any): FundamentalPoint | null { if (!row || typeof row !== 'object') return null; const time = this.fundDate(row); const eps = Number(row.earnings_per_share ?? row.eps ?? row.reportedEPS ?? row.dilutedEPS); const bvps = Number(row.book_value_per_share ?? row.bvps ?? row.bookValuePerShare); if (!time || !isFinite(eps) || !isFinite(bvps)) return null; return { time, earnings_per_share: eps, book_value_per_share: bvps }; }
 private extractFundamentalPoints(data: TickerData): FundamentalPoint[] { const bags: any[] = []; for (const arr of [data.raw?.fundamentals, data.raw?.metrics, data.raw?.financials, data.fundamentals, data.metrics]) { if (Array.isArray(arr)) bags.push(...arr); } const points = bags.map(r => this.toFundPoint(r)).filter((p): p is FundamentalPoint => !!p); const snap = data.snapshot?.snapshot; if (snap) { const dated = this.toFundPoint({ ...snap, as_of: snap.as_of || snap.report_date || snap.period_end || snap.date || snap.time || data.snapshot?.as_of }); if (dated) points.push(dated); } points.sort((a, b) => new Date(a.time).getTime() - new Date(b.time).getTime()); return points; }
 loadData() { console.log(`Loading data for ${TICKERS.length} tickers...`); ["FEDFUNDS", "GDP", "UNRATE", "CPIAUCSL"].forEach(sid => { const p = path.join(LAKE_PATH, `fred/raw/${sid}/${sid}.csv`); if (fs.existsSync(p)) { const content = fs.readFileSync(p, 'utf8'); const lines = content.split('\n').filter(l => l.trim() !== "").slice(1); const data = lines.map(l => { const parts = l.split(','); return { observation_date: parts[2], observation_value: parseFloat(parts[3]) }; }).filter(d => !isNaN(d.observation_value)); this.macroHistory.set(sid, data); } }); TICKERS.forEach(t => { const p = path.join(LAKE_PATH, `finance_bridge/expanded_universe/${t}.json`); if (fs.existsSync(p)) { try { const data = JSON.parse(fs.readFileSync(p, 'utf8')) as TickerData; if (data) { this.fundamentalHistory.set(t, data); this.fundamentalPoints.set(t, this.extractFundamentalPoints(data)); if (data.raw && data.raw.prices) this.priceHistory.set(t, data.raw.prices); } } catch(e) {} } }); }
 getRegimeScore(date: Date): number { const ff = this.macroHistory.get("FEDFUNDS"); if (!ff) return 0; const past = ff.filter(d => new Date(d.observation_date) <= date); const latest = past[past.length - 1]; return (latest?.observation_value || 0) < 5 ? -1 : 1; }
 getPointInTimeFundamentals(ticker: string, date: Date): FundamentalPoint | null { const points = this.fundamentalPoints.get(ticker); if (!points || points.length === 0) return null; const past = points.filter(p => new Date(p.time) <= date); return past.length ? past[past.length - 1] : null; }
 calculateIntrinsicValue(ticker: string, date: Date): number { const snap = this.getPointInTimeFundamentals(ticker, date); if (!snap) return 0; return ((snap.earnings_per_share || 0) * 30 + (snap.book_value_per_share || 0) * 2); }
 getPrice(ticker: string, date: Date): number { const prices = this.priceHistory.get(ticker); if (!prices) return 0; const past = prices.filter(p => new Date(p.time) <= date); const match = past[past.length - 1]; return match ? match.close : 0; }
 run() { this.loadData(); let current = new Date(START_DATE); while (current <= END_DATE) { const regime = this.getRegimeScore(current); const targetWeight = regime < 0 ? 0.8 : 0.6; const candidates: {ticker: string, price: number}[] = []; TICKERS.forEach(t => { const intrinsic = this.calculateIntrinsicValue(t, current); const price = this.getPrice(t, current); if (price > 0 && intrinsic > 0) { const mos = (intrinsic - price) / price; if (mos > -0.5) candidates.push({ticker: t, price}); } }); this.rebalance(candidates, targetWeight, current); let equityValue = 0; this.portfolio.positions.forEach((shares, t) => { equityValue += shares * this.getPrice(t, current); }); this.history.push({ date: current.toISOString().split('T')[0], cash: this.portfolio.cash, equityValue, totalValue: this.portfolio.cash + equityValue, regime, positionCount: this.portfolio.positions.size }); current.setMonth(current.getMonth() + 1); } this.save(); }
 rebalance(candidates: {ticker: string, price: number}[], targetWeight: number, date: Date) { let totalValue = this.portfolio.cash; this.portfolio.positions.forEach((shares, t) => { const p = this.getPrice(t, date); if (p > 0) totalValue += shares * p; }); const targetEquity = totalValue * targetWeight; const candTickers = candidates.map(c => c.ticker); this.portfolio.positions.forEach((shares, t) => { if (!candTickers.includes(t)) { const p = this.getPrice(t, date); if (p > 0) { this.portfolio.cash += shares * p; this.portfolio.positions.delete(t); } } }); if (candidates.length > 0) { const perStock = targetEquity / candidates.length; candidates.forEach(c => { const currentShares = this.portfolio.positions.get(c.ticker) || 0; const currentVal = currentShares * c.price; const diff = perStock - currentVal; if (diff > 0 && this.portfolio.cash >= diff) { this.portfolio.positions.set(c.ticker, currentShares + diff / c.price); this.portfolio.cash -= diff; } else if (diff < 0) { const sellShares = Math.min(currentShares, Math.abs(diff) / c.price); this.portfolio.positions.set(c.ticker, currentShares - sellShares); this.portfolio.cash += sellShares * c.price; } }); } }
 save() { const initialCapital = 1000000; const final = this.history[this.history.length - 1]; const totalReturn = final ? (final.totalValue - initialCapital) / initialCapital : 0; const outcome = { meta: { generated_at: new Date().toISOString(), start_date: START_DATE.toISOString().split('T')[0], end_date: END_DATE.toISOString().split('T')[0], initial_capital: initialCapital, tickers: TICKERS, point_in_time_fundamentals: true }, metrics: { total_return: totalReturn, ending_value: final?.totalValue ?? initialCapital, final_cash: final?.cash ?? initialCapital, final_equity: final?.equityValue ?? 0 }, history: this.history }; if (!fs.existsSync(LAKE_PATH)) fs.mkdirSync(LAKE_PATH, { recursive: true }); const out = path.join(LAKE_PATH, "backtest_results.json"); fs.writeFileSync(out, JSON.stringify(outcome, null, 2)); console.log(`Results saved to ${out}`); if (final) { console.log(`Final Portfolio Value: $${final.totalValue.toLocaleString()}`); console.log(`Final Cash: $${final.cash.toLocaleString()}`); console.log(`Final Equity: $${final.equityValue.toLocaleString()}`); console.log(`Total Return: ${(totalReturn * 100).toFixed(2)}%`); } }
}
new BacktestRunner().run();