"""Source registry — every provider/source, its rights, quota, and what
decision coverage it improves.

The acquisition metric is "how much does this source improve decision coverage
or our ability to validate a decision model?", not "how many rows did we
scrape?". Each row records access status honestly; a keyed or terms-review
source is reported as such and never bypassed.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any

from ..acquisition.contracts import utc_now
from ..acquisition.automation import automation_status

SOURCE_REGISTRY_V1: list[dict[str, Any]] = [
    # ---- EVENT_GRAPH -----------------------------------------------------
    {
        "source_id": "musicbrainz",
        "source_name": "MusicBrainz",
        "source_kind": "IDENTITY",
        "pipeline": "EVENT_GRAPH",
        "provider": "musicbrainz",
        "access_status": "AVAILABLE",
        "documented_quota": "1 req/s; CC0 dumps for local ingestion",
        "rights_status": "OPEN_COMMERCIAL_OK",
        "commercial_use_status": "OPEN_COMMERCIAL_OK",
        "license": "CC0 (core DB + specified dumps)",
        "coverage_contribution": "artist/venue identity backbone; cross-source entity resolution",
        "notes": "Use as primary identity layer, not a transient API dependency.",
    },
    {
        "source_id": "ticketmaster-discovery",
        "source_name": "Ticketmaster Discovery",
        "source_kind": "EVENT_GRAPH",
        "pipeline": "EVENT_GRAPH",
        "provider": "ticketmaster",
        "access_status": "KEY_REQUIRED",
        "documented_quota": "5,000 calls/day; 5 req/s; 230k+ events exposed",
        "rights_status": "TERMS_REVIEW_REQUIRED",
        "commercial_use_status": "TERMS_REVIEW_REQUIRED",
        "license": "Ticketmaster Developer terms",
        "coverage_contribution": "forward event spine: artist/venue/geography/promoter searches",
        "notes": "Discovery API is NOT an internal TM1 ticket-count feed.",
    },
    {
        "source_id": "jambase",
        "source_name": "JamBase Data",
        "source_kind": "EVENT_GRAPH",
        "pipeline": "EVENT_GRAPH",
        "provider": "jambase",
        "access_status": "TERMS_REVIEW",
        "documented_quota": "5M+ performances, 616k artists, 91k venues, 20k festivals",
        "rights_status": "TERMS_REVIEW_REQUIRED",
        "commercial_use_status": "TERMS_REVIEW_REQUIRED",
        "license": "Commercial terms to be evaluated",
        "coverage_contribution": "historical event/venue topology; IDs mapped to MusicBrainz/Ticketmaster",
        "notes": "Does not provide outcome labels; evaluate terms before contracting.",
    },
    {
        "source_id": "common-crawl",
        "source_name": "Common Crawl",
        "source_kind": "EVENT_GRAPH",
        "pipeline": "EVENT_GRAPH",
        "provider": "commoncrawl",
        "access_status": "AVAILABLE",
        "documented_quota": "Web archive index + extracted text; free",
        "rights_status": "OPEN_COMMERCIAL_OK",
        "commercial_use_status": "OPEN_COMMERCIAL_OK",
        "license": "CC0 index; rights of underlying pages remain source-specific",
        "coverage_contribution": "historical reconstruction: festival sites, tour pages, venue calendars, pricing/onsale pages",
        "notes": "Domain- and entity-directed retrieval; rights tracked per page in the registry.",
    },
    # ---- OUTCOME_HUNTER ---------------------------------------------------
    {
        "source_id": "billboard-boxscore",
        "source_name": "Billboard Boxscore",
        "source_kind": "OUTCOME",
        "pipeline": "OUTCOME_HUNTER",
        "provider": "billboard",
        "access_status": "AVAILABLE",
        "documented_quota": "archived chart pages (research corpus)",
        "rights_status": "RESEARCH_ONLY",
        "commercial_use_status": "RESEARCH_ONLY",
        "license": "Editorial chart; research use only",
        "coverage_contribution": "REPORTED_ATTENDANCE / TICKET_GROSS outcome claims",
        "notes": "Chart/editorial selection bias documented in baseline research.",
    },
    {
        "source_id": "pollstar-hot-tickets",
        "source_name": "Pollstar Hot Tickets",
        "source_kind": "OUTCOME",
        "pipeline": "OUTCOME_HUNTER",
        "provider": "pollstar",
        "access_status": "AVAILABLE",
        "documented_quota": "archived chart pages (research corpus)",
        "rights_status": "RESEARCH_ONLY",
        "commercial_use_status": "RESEARCH_ONLY",
        "license": "Editorial chart; research use only",
        "coverage_contribution": "PAID_TICKETS / capacity-tier outcome claims",
        "notes": "PAID_TICKETS per Pollstar reporting policy; never relabeled.",
    },
    {
        "source_id": "touring-data",
        "source_name": "Touring Data",
        "source_kind": "OUTCOME",
        "pipeline": "OUTCOME_HUNTER",
        "provider": "touring_data",
        "access_status": "TERMS_REVIEW",
        "documented_quota": "reported tour pages",
        "rights_status": "TERMS_REVIEW_REQUIRED",
        "commercial_use_status": "TERMS_REVIEW_REQUIRED",
        "license": "Subscription/reporting terms",
        "coverage_contribution": "REPORTED_ATTENDANCE / TICKET_GROSS claims with tour identity",
        "notes": "Reported rows only; estimated rows never promoted.",
    },
    {
        "source_id": "setlistfm",
        "source_name": "Setlist.fm",
        "source_kind": "OUTCOME",
        "pipeline": "OUTCOME_HUNTER",
        "provider": "setlistfm",
        "access_status": "KEY_REQUIRED",
        "documented_quota": "API key via registration",
        "rights_status": "TERMS_REVIEW_REQUIRED",
        "commercial_use_status": "TERMS_REVIEW_REQUIRED",
        "license": "Setlist.fm API terms",
        "coverage_contribution": "performance confirmation (EVENT_PERFORMED) and venue/config evidence",
        "notes": "Setlist presence is NOT attendance.",
    },
    # ---- CONTEXT_PANEL ----------------------------------------------------
    {
        "source_id": "wikimedia-pageviews",
        "source_name": "Wikimedia Pageviews",
        "source_kind": "CONTEXT",
        "pipeline": "CONTEXT_PANEL",
        "provider": "wikimedia",
        "access_status": "AVAILABLE",
        "documented_quota": "key-free; historical from 2015-07-01",
        "rights_status": "OPEN_WITH_ATTRIBUTION",
        "commercial_use_status": "OPEN_WITH_ATTRIBUTION",
        "license": "CC-BY-SA / CC0 aggregate data",
        "coverage_contribution": "daily artist attention panel: velocity, shocks, decay",
        "notes": "Stored as daily series, not one current score.",
    },
    {
        "source_id": "gdelt",
        "source_name": "GDELT",
        "source_kind": "CONTEXT",
        "pipeline": "CONTEXT_PANEL",
        "provider": "gdelt",
        "access_status": "AVAILABLE",
        "documented_quota": "free/open daily datasets",
        "rights_status": "OPEN_COMMERCIAL_OK",
        "commercial_use_status": "OPEN_COMMERCIAL_OK",
        "license": "GDELT terms (free academic/commercial/government)",
        "coverage_contribution": "news counts, controversy/cancellation topics, media geography",
        "notes": "Aggregate counts and topic signals only.",
    },
    {
        "source_id": "google-trends",
        "source_name": "Google Trends API",
        "source_kind": "CONTEXT",
        "pipeline": "CONTEXT_PANEL",
        "provider": "google_trends",
        "access_status": "REGISTRATION_REQUIRED",
        "documented_quota": "application-based alpha (as of Aug 2026)",
        "rights_status": "TERMS_REVIEW_REQUIRED",
        "commercial_use_status": "TERMS_REVIEW_REQUIRED",
        "license": "Google developer terms",
        "coverage_contribution": "search-interest attention panel",
        "notes": "Apply for the official API; scraping is not an architectural dependency.",
    },
    {
        "source_id": "youtube",
        "source_name": "YouTube Data API",
        "source_kind": "CONTEXT",
        "pipeline": "CONTEXT_PANEL",
        "provider": "youtube",
        "access_status": "KEY_REQUIRED",
        "documented_quota": "10,000 units/day default",
        "rights_status": "TERMS_REVIEW_REQUIRED",
        "commercial_use_status": "TERMS_REVIEW_REQUIRED",
        "license": "YouTube API terms",
        "coverage_contribution": "fan-generated comment volume (real social signal)",
        "notes": "Existing fan-signal collection continues.",
    },
    {
        "source_id": "bluesky-firehose",
        "source_name": "Bluesky Firehose",
        "source_kind": "CONTEXT",
        "pipeline": "CONTEXT_PANEL",
        "provider": "bluesky",
        "access_status": "AVAILABLE",
        "documented_quota": "public update stream",
        "rights_status": "TERMS_REVIEW_REQUIRED",
        "commercial_use_status": "TERMS_REVIEW_REQUIRED",
        "license": "Bluesky ToS / source-specific",
        "coverage_contribution": "forward attention events",
        "notes": "Evaluate terms before committing to a persistent collection.",
    },
    {
        "source_id": "census",
        "source_name": "U.S. Census Bureau",
        "source_kind": "CONTEXT",
        "pipeline": "CONTEXT_PANEL",
        "provider": "census",
        "access_status": "KEY_REQUIRED",
        "documented_quota": "API key required for Census Data API (since May 2026)",
        "rights_status": "OPEN_COMMERCIAL_OK",
        "commercial_use_status": "OPEN_COMMERCIAL_OK",
        "license": "U.S. government public data",
        "coverage_contribution": "population, age bands, income, growth by metro (ACS 5-year)",
        "notes": "Store the vintage (e.g. ACS 5-Year 2018-2022); never backdate revisions.",
    },
    {
        "source_id": "bls",
        "source_name": "Bureau of Labor Statistics",
        "source_kind": "CONTEXT",
        "pipeline": "CONTEXT_PANEL",
        "provider": "bls",
        "access_status": "KEY_REQUIRED",
        "documented_quota": "public data API + QCEW downloads",
        "rights_status": "OPEN_COMMERCIAL_OK",
        "commercial_use_status": "OPEN_COMMERCIAL_OK",
        "license": "U.S. government public data",
        "coverage_contribution": "employment, unemployment, wage growth, hospitality employment",
        "notes": "Series vintages matter; store the vintage with every row.",
    },
    {
        "source_id": "bea",
        "source_name": "Bureau of Economic Analysis",
        "source_kind": "CONTEXT",
        "pipeline": "CONTEXT_PANEL",
        "provider": "bea",
        "access_status": "AVAILABLE",
        "documented_quota": "regional accounts; metro/state RPP",
        "rights_status": "OPEN_COMMERCIAL_OK",
        "commercial_use_status": "OPEN_COMMERCIAL_OK",
        "license": "U.S. government public data",
        "coverage_contribution": "regional income, GDP, regional price parities",
        "notes": "Clean, reproducible, comparatively inexpensive.",
    },
    {
        "source_id": "noaa-cdo",
        "source_name": "NOAA Climate Data Online",
        "source_kind": "CONTEXT",
        "pipeline": "CONTEXT_PANEL",
        "provider": "noaa",
        "access_status": "KEY_REQUIRED",
        "documented_quota": "10,000 requests/day per token; 5 req/s",
        "rights_status": "OPEN_COMMERCIAL_OK",
        "commercial_use_status": "OPEN_COMMERCIAL_OK",
        "license": "U.S. government public data",
        "coverage_contribution": "historical weather: temperature, precipitation, extremes",
        "notes": "Actual weather explains outcomes; forecast-at-cutoff is separate.",
    },
    {
        "source_id": "era5",
        "source_name": "ERA5 Reanalysis",
        "source_kind": "CONTEXT",
        "pipeline": "CONTEXT_PANEL",
        "provider": "era5",
        "access_status": "REGISTRATION_REQUIRED",
        "documented_quota": "hourly reanalysis back to 1940 (Climate Data Store)",
        "rights_status": "TERMS_REVIEW_REQUIRED",
        "commercial_use_status": "TERMS_REVIEW_REQUIRED",
        "license": "Copernicus CDS terms",
        "coverage_contribution": "globally consistent backtesting weather",
        "notes": "Registration required; same actual-vs-forecast separation applies.",
    },
    # ---- FORWARD_WATCH ----------------------------------------------------
    {
        "source_id": "seatgeek",
        "source_name": "SeatGeek",
        "source_kind": "FORWARD",
        "pipeline": "FORWARD_WATCH",
        "provider": "seatgeek",
        "access_status": "KEY_REQUIRED",
        "documented_quota": "client id/secret via registration",
        "rights_status": "TERMS_REVIEW_REQUIRED",
        "commercial_use_status": "TERMS_REVIEW_REQUIRED",
        "license": "SeatGeek API terms",
        "coverage_contribution": "secondary listing counts and price aggregates",
        "notes": "Secondary buyer prices; never labeled as primary inventory.",
    },
    # ---- PRIVATE / BACKTEST ------------------------------------------------
    {
        "source_id": "eventbrite-partner",
        "source_name": "Eventbrite (first-party)",
        "source_kind": "PRIVATE",
        "pipeline": "BACKTEST",
        "provider": "eventbrite",
        "access_status": "PARTNER_GATED",
        "documented_quota": "authenticated organizer access; order model links to ticket classes",
        "rights_status": "OPEN_COMMERCIAL_OK",
        "commercial_use_status": "OPEN_COMMERCIAL_OK",
        "license": "Eventbrite partner terms + customer consent",
        "coverage_contribution": "first-party ticket exports, settlement, P&L",
        "notes": "Customer-connected data is where the flywheel gets serious.",
    },
    {
        "source_id": "customer-exports",
        "source_name": "Customer ticket/settlement exports",
        "source_kind": "PRIVATE",
        "pipeline": "BACKTEST",
        "provider": "customer",
        "access_status": "PARTNER_GATED",
        "documented_quota": "30-100 anonymized settled shows per pilot",
        "rights_status": "OPEN_COMMERCIAL_OK",
        "commercial_use_status": "OPEN_COMMERCIAL_OK",
        "license": "Customer data agreement; PII quarantined",
        "coverage_contribution": "real outcomes, costs, guarantees, decision timestamps",
        "notes": "Design-partner importer already supports this workflow.",
    },
]


def source_rows(*, registered_at: datetime | None = None) -> list[dict[str, Any]]:
    """Return registry rows ready for ``flywheel.source_registry`` insert."""
    now = (registered_at or utc_now()).isoformat()
    return [
        {
            "source_id": row["source_id"],
            "source_name": row["source_name"],
            "source_kind": row["source_kind"],
            "pipeline": row["pipeline"],
            "provider": row.get("provider"),
            "access_status": row["access_status"],
            "documented_quota": row.get("documented_quota"),
            "rights_status": row["rights_status"],
            "commercial_use_status": row["commercial_use_status"],
            "automation_status": automation_status(row.get("provider") or row["source_id"]).value,
            "license": row.get("license"),
            "coverage_contribution": row.get("coverage_contribution"),
            "notes": row.get("notes"),
            "registered_at": now,
            "updated_at": now,
        }
        for row in SOURCE_REGISTRY_V1
    ]
