"""Market economics evidence: capacity claims, ticket snapshots, outcomes."""

from .capacity import (
    CapacityClaim,
    average_capacity,
    claim_from_wikipedia_infobox,
    compute_utilization,
    mark_conflicts,
    select_applicable_capacity,
)
from .collector import CollectorLock, LockHeldError, snapshot_event, snapshot_upcoming
from .compare import compare_primary_secondary
from .enrichment import CapacityEnricher
from .outcomes import infer_sold_out_from_listing_count, infer_sold_out_from_offsale
from .repository import EconomicsRepository
from .runlog import (
    EXIT_AUTH_FAILURE,
    EXIT_ERROR,
    EXIT_LOCK_HELD,
    EXIT_NO_ACTIVE_EVENTS,
    EXIT_SUCCESS,
    persist_run_to_db,
    PROVIDER_AUTH_FAILED,
    PROVIDER_AUTH_VALID,
    PROVIDER_ERROR,
    PROVIDER_NOT_CONFIGURED,
    PROVIDER_RATE_LIMITED,
    RunLogger,
    SOFTWARE_VERSION,
)
from .snapshots import (
    describe_price_change,
    primary_snapshots_from_ticketmaster,
    secondary_snapshot_from_seatgeek,
    snapshot_change_semantics,
    snapshot_deltas,
)
from .tracking import (
    TRACKING_ACTIVE,
    TRACKING_CANCELED,
    TRACKING_COMPLETED,
    TRACKING_EXPIRED,
    TRACKING_PAUSED,
    TRACKING_STATUSES,
    TrackedEvent,
    TrackedEventRegistry,
)
from .venues import (
    RESOLUTION_ALIAS_MATCH,
    RESOLUTION_COORDINATE_MATCH,
    RESOLUTION_EXACT_CANONICAL_MAPPING,
    RESOLUTION_EXACT_EXTERNAL_ID,
    RESOLUTION_EXACT_NAME_CITY,
    RESOLUTION_FUZZY_REVIEW_REQUIRED,
    RESOLUTION_UNRESOLVED,
    VenueResolver,
    merge_united_center,
)

__all__ = [
    "CapacityClaim",
    "EconomicsRepository",
    "TrackedEvent",
    "TrackedEventRegistry",
    "VenueResolver",
    "CapacityEnricher",
    "CollectorLock",
    "LockHeldError",
    "RunLogger",
    "average_capacity",
    "claim_from_wikipedia_infobox",
    "compare_primary_secondary",
    "compute_utilization",
    "describe_price_change",
    "infer_sold_out_from_listing_count",
    "infer_sold_out_from_offsale",
    "mark_conflicts",
    "merge_united_center",
    "persist_run_to_db",
    "primary_snapshots_from_ticketmaster",
    "secondary_snapshot_from_seatgeek",
    "select_applicable_capacity",
    "snapshot_change_semantics",
    "snapshot_deltas",
    "snapshot_event",
    "snapshot_upcoming",
    "TRACKING_ACTIVE",
    "TRACKING_CANCELED",
    "TRACKING_COMPLETED",
    "TRACKING_EXPIRED",
    "TRACKING_PAUSED",
    "TRACKING_STATUSES",
    "RESOLUTION_ALIAS_MATCH",
    "RESOLUTION_COORDINATE_MATCH",
    "RESOLUTION_EXACT_CANONICAL_MAPPING",
    "RESOLUTION_EXACT_EXTERNAL_ID",
    "RESOLUTION_EXACT_NAME_CITY",
    "RESOLUTION_FUZZY_REVIEW_REQUIRED",
    "RESOLUTION_UNRESOLVED",
    "EXIT_SUCCESS",
    "EXIT_ERROR",
    "EXIT_LOCK_HELD",
    "EXIT_AUTH_FAILURE",
    "EXIT_NO_ACTIVE_EVENTS",
    "PROVIDER_AUTH_VALID",
    "PROVIDER_NOT_CONFIGURED",
    "PROVIDER_AUTH_FAILED",
    "PROVIDER_RATE_LIMITED",
    "PROVIDER_ERROR",
    "SOFTWARE_VERSION",
]
